### ISSUE TITLE
error

### ISSUE THREAD

**Issue by wm901115nwpu** [EE202B/RenderScriptNDK#2]
ERROR: /home/wangmeng/RSTensorFlow_mobile/tensorflow/examples/android/BUILD:67:1: Building tensorflow/examples/android/libtensorflow_demo.jar (21 source files) failed: Worker process sent response with exit code: 1.
tensorflow/examples/android/src/org/tensorflow/demo/DetectorActivity.java:50: error: DetectorActivity is not abstract and does not override abstract method getDesiredPreviewFrameSize() in CameraActivity
public class DetectorActivity extends CameraActivity implements OnImageAvailableListener {
       ^
tensorflow/examples/android/src/org/tensorflow/demo/DetectorActivity.java:380: error: getDesiredPreviewFrameSize() in DetectorActivity cannot override getDesiredPreviewFrameSize() in CameraActivity
  protected Size getDesiredPreviewFrameSize() {
                 ^
  return type Size is not compatible with int
tensorflow/examples/android/src/org/tensorflow/demo/DetectorActivity.java:145: error: incompatible types: DetectorActivity cannot be converted to DisplayMetrics
    tracker = new MultiBoxTracker(this);
                                  ^
tensorflow/examples/android/src/org/tensorflow/demo/DetectorActivity.java:299: error: method convertYUV420ToARGB8888 in class ImageUtils cannot be applied to given types;
      ImageUtils.convertYUV420ToARGB8888(
                ^
  required: byte[],byte[],byte[],int[],int,int,int,int,int,boolean
  found: byte[],byte[],byte[],int,int,int,int,int,int[]
  reason: actual and formal argument lists differ in length
tensorflow/examples/android/src/org/tensorflow/demo/DetectorActivity.java:379: error: method does not override or implement a method from a supertype
  @Override
  ^
tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowSingleShotDetector.java:68: error: constructor TensorFlowInferenceInterface in class TensorFlowInferenceInterface cannot be applied to given types;
    d.inferenceInterface = new TensorFlowInferenceInterface(assetManager, modelFilename);
                           ^
  required: no arguments
  found: AssetManager,String
  reason: actual and formal argument lists differ in length
tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowSingleShotDetector.java:69: error: cannot find symbol
    d.labels = (new LabelMap()).loadFromAssets(assetManager, labelsFilename);
                    ^
  symbol:   class LabelMap
  location: class TensorFlowSingleShotDetector
tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowSingleShotDetector.java:98: error: cannot find symbol
    inferenceInterface.feed(inputName, bytePixels, 1, inputSize, inputSize, 3);
                      ^
  symbol:   method feed(String,byte[],int,int,int,int)
  location: variable inferenceInterface of type TensorFlowInferenceInterface
tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowSingleShotDetector.java:105: error: cannot find symbol
    inferenceInterface.run(outputNames, logStats);
                      ^
  symbol:   method run(String[],boolean)
  location: variable inferenceInterface of type TensorFlowInferenceInterface
tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowSingleShotDetector.java:114: error: cannot find symbol
    inferenceInterface.fetch(outputNames[3], numDetectionsArray);
                      ^
  symbol:   method fetch(String,float[])
  location: variable inferenceInterface of type TensorFlowInferenceInterface
tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowSingleShotDetector.java:119: error: cannot find symbol
    inferenceInterface.fetch(outputNames[0], boxes);
                      ^
  symbol:   method fetch(String,float[])
  location: variable inferenceInterface of type TensorFlowInferenceInterface
tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowSingleShotDetector.java:120: error: cannot find symbol
    inferenceInterface.fetch(outputNames[1], scores);
                      ^
  symbol:   method fetch(String,float[])
  location: variable inferenceInterface of type TensorFlowInferenceInterface
tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowSingleShotDetector.java:121: error: cannot find symbol
    inferenceInterface.fetch(outputNames[2], classes);
                      ^
  symbol:   method fetch(String,float[])
  location: variable inferenceInterface of type TensorFlowInferenceInterface
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
Target //tensorflow/examples/android:tensorflow_demo failed to build
Use --verbose_failures to see the command lines of failed build steps.

**Comment by coroner4817** [comment]
1, This build error is not from this project
2, To build RSTensorflow you must meet all the version requirements as I stated
3, This error comes from the original TF android demo code, you should ask in the TF repo
4, Google it before throwing an issue
