### ISSUE TITLE
RenderScript.h

### ISSUE THREAD

**Issue by Yair0007** [EE202B/RenderScriptNDK#3]
I'm having trouble with RS headers. How can I get RenderScript.h ? thanks a lot

**Comment by coroner4817** [comment]
1, Make sure your Android.mk has include the RS module at the end.
2, Make sure your NDK version>=r14.
3, If still not working try `<cpp/RenderScript.h>` , but this shouldn't be the solution if you include the module correctly.

**Comment by Yair0007** [comment]
After including the RS module I get:
Android NDK: jni/Android.mk: Cannot find module with tag 'android/renderscript' in import path    
Android NDK: Are you sure your NDK_MODULE_PATH variable is properly defined ?
Thanks again

**Comment by coroner4817** [comment]
So basically run `find . -name RenderScript.h` at your NDK root.
If not find under current NDK, update your NDK.
If find you can copy it your project folder and manually link it. 

Clone this [repo](https://github.com/EE202B/RenderScriptOps) on your machine, if still not working means that your NDK is not set properly.
